# Generated by Django 3.2.3 on 2024-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240107_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(verbose_name='картинка'),
        ),
    ]
