# Generated by Django 3.2.3 on 2024-01-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscription_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscriptions',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='cannot_subscribe_to_self',
        ),
    ]
